[package]
name = "api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
name = "libapi"

[[bin]]
path = "src/bin/main.rs"
name = "api"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "0d53e23" }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "migrate", "uuid", "json" ] }
